# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Manual implementation for demo purposes
# In production, generate with: python -m grpc_tools.protoc -I../../proto --python_out=. --grpc_python_out=. ../../proto/trading.proto

from dataclasses import dataclass
from typing import List


@dataclass
class MarketData:
    symbol: str = ""
    price: float = 0.0
    volume: float = 0.0
    timestamp: int = 0


@dataclass
class OrderRequest:
    id: str = ""
    symbol: str = ""
    side: str = ""
    type: str = ""
    quantity: float = 0.0
    price: float = 0.0


@dataclass
class OrderResponse:
    order_id: str = ""
    symbol: str = ""
    side: str = ""
    status: str = ""
    quantity: float = 0.0
    price: float = 0.0
    created_at: int = 0
    error: str = ""


@dataclass
class CancelOrderRequest:
    order_id: str = ""
    symbol: str = ""


@dataclass
class CancelOrderResponse:
    success: bool = False
    message: str = ""


@dataclass
class BotStatusResponse:
    is_active: bool = False
    started_at: int = 0
    stopped_at: int = 0
    total_trades: int = 0
    total_profit: float = 0.0


@dataclass
class SubscribeRequest:
    symbols: List[str] = None
    
    def __post_init__(self):
        if self.symbols is None:
            self.symbols = []


@dataclass
class GetBotStatusRequest:
    pass


@dataclass
class StartBotRequest:
    pass


@dataclass
class StartBotResponse:
    success: bool = False
    message: str = ""


@dataclass
class StopBotRequest:
    pass


@dataclass
class StopBotResponse:
    success: bool = False
    message: str = ""
