# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import infrastructure.grpc.trading_pb2 as trading__pb2




class MarketDataServiceStub(object):
    """Market Data Service - Stream market data from Go to Python
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeMarketData = channel.unary_stream(
                '/tradingbot.MarketDataService/SubscribeMarketData',
                request_serializer=trading__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=trading__pb2.MarketData.FromString,
                _registered_method=True)


class MarketDataServiceServicer(object):
    """Market Data Service - Stream market data from Go to Python
    """

    def SubscribeMarketData(self, request, context):
        """Subscribe to market data stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeMarketData': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeMarketData,
                    request_deserializer=trading__pb2.SubscribeRequest.FromString,
                    response_serializer=trading__pb2.MarketData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tradingbot.MarketDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tradingbot.MarketDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarketDataService(object):
    """Market Data Service - Stream market data from Go to Python
    """

    @staticmethod
    def SubscribeMarketData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tradingbot.MarketDataService/SubscribeMarketData',
            trading__pb2.SubscribeRequest.SerializeToString,
            trading__pb2.MarketData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OrderExecutionServiceStub(object):
    """Order Execution Service - Execute orders from Python to Go
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteOrder = channel.unary_unary(
                '/tradingbot.OrderExecutionService/ExecuteOrder',
                request_serializer=trading__pb2.OrderRequest.SerializeToString,
                response_deserializer=trading__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/tradingbot.OrderExecutionService/CancelOrder',
                request_serializer=trading__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=trading__pb2.CancelOrderResponse.FromString,
                _registered_method=True)


class OrderExecutionServiceServicer(object):
    """Order Execution Service - Execute orders from Python to Go
    """

    def ExecuteOrder(self, request, context):
        """Execute a trading order
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Cancel an order
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderExecutionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteOrder,
                    request_deserializer=trading__pb2.OrderRequest.FromString,
                    response_serializer=trading__pb2.OrderResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=trading__pb2.CancelOrderRequest.FromString,
                    response_serializer=trading__pb2.CancelOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tradingbot.OrderExecutionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tradingbot.OrderExecutionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderExecutionService(object):
    """Order Execution Service - Execute orders from Python to Go
    """

    @staticmethod
    def ExecuteOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradingbot.OrderExecutionService/ExecuteOrder',
            trading__pb2.OrderRequest.SerializeToString,
            trading__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradingbot.OrderExecutionService/CancelOrder',
            trading__pb2.CancelOrderRequest.SerializeToString,
            trading__pb2.CancelOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BotStatusServiceStub(object):
    """Bot Status Service - Get bot status from Go
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBotStatus = channel.unary_unary(
                '/tradingbot.BotStatusService/GetBotStatus',
                request_serializer=trading__pb2.GetBotStatusRequest.SerializeToString,
                response_deserializer=trading__pb2.BotStatusResponse.FromString,
                _registered_method=True)
        self.StartBot = channel.unary_unary(
                '/tradingbot.BotStatusService/StartBot',
                request_serializer=trading__pb2.StartBotRequest.SerializeToString,
                response_deserializer=trading__pb2.StartBotResponse.FromString,
                _registered_method=True)
        self.StopBot = channel.unary_unary(
                '/tradingbot.BotStatusService/StopBot',
                request_serializer=trading__pb2.StopBotRequest.SerializeToString,
                response_deserializer=trading__pb2.StopBotResponse.FromString,
                _registered_method=True)


class BotStatusServiceServicer(object):
    """Bot Status Service - Get bot status from Go
    """

    def GetBotStatus(self, request, context):
        """Get current bot status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartBot(self, request, context):
        """Start the bot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopBot(self, request, context):
        """Stop the bot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BotStatusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBotStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBotStatus,
                    request_deserializer=trading__pb2.GetBotStatusRequest.FromString,
                    response_serializer=trading__pb2.BotStatusResponse.SerializeToString,
            ),
            'StartBot': grpc.unary_unary_rpc_method_handler(
                    servicer.StartBot,
                    request_deserializer=trading__pb2.StartBotRequest.FromString,
                    response_serializer=trading__pb2.StartBotResponse.SerializeToString,
            ),
            'StopBot': grpc.unary_unary_rpc_method_handler(
                    servicer.StopBot,
                    request_deserializer=trading__pb2.StopBotRequest.FromString,
                    response_serializer=trading__pb2.StopBotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tradingbot.BotStatusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tradingbot.BotStatusService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BotStatusService(object):
    """Bot Status Service - Get bot status from Go
    """

    @staticmethod
    def GetBotStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradingbot.BotStatusService/GetBotStatus',
            trading__pb2.GetBotStatusRequest.SerializeToString,
            trading__pb2.BotStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartBot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradingbot.BotStatusService/StartBot',
            trading__pb2.StartBotRequest.SerializeToString,
            trading__pb2.StartBotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopBot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradingbot.BotStatusService/StopBot',
            trading__pb2.StopBotRequest.SerializeToString,
            trading__pb2.StopBotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
