# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Manual implementation for demo purposes

import grpc
from typing import Iterator, Callable

from infrastructure.grpc.trading_pb2 import (
    OrderRequest,
    OrderResponse,
    CancelOrderRequest,
    CancelOrderResponse,
    BotStatusResponse,
    GetBotStatusRequest,
    StartBotRequest,
    StartBotResponse,
    StopBotRequest,
    StopBotResponse,
    SubscribeRequest,
    MarketData,
)


class OrderExecutionServiceStub:
    """Stub for Order Execution Service."""
    
    def __init__(self, channel: grpc.Channel):
        self.channel = channel
        self.ExecuteOrder = channel.unary_unary(
            '/tradingbot.OrderExecutionService/ExecuteOrder',
            request_serializer=lambda x: x,
            response_deserializer=lambda x: x,
        )
        self.CancelOrder = channel.unary_unary(
            '/tradingbot.OrderExecutionService/CancelOrder',
            request_serializer=lambda x: x,
            response_deserializer=lambda x: x,
        )


class BotStatusServiceStub:
    """Stub for Bot Status Service."""
    
    def __init__(self, channel: grpc.Channel):
        self.channel = channel
        self.GetBotStatus = channel.unary_unary(
            '/tradingbot.BotStatusService/GetBotStatus',
            request_serializer=lambda x: x,
            response_deserializer=lambda x: x,
        )
        self.StartBot = channel.unary_unary(
            '/tradingbot.BotStatusService/StartBot',
            request_serializer=lambda x: x,
            response_deserializer=lambda x: x,
        )
        self.StopBot = channel.unary_unary(
            '/tradingbot.BotStatusService/StopBot',
            request_serializer=lambda x: x,
            response_deserializer=lambda x: x,
        )


class MarketDataServiceStub:
    """Stub for Market Data Service."""
    
    def __init__(self, channel: grpc.Channel):
        self.channel = channel
        self.SubscribeMarketData = channel.unary_stream(
            '/tradingbot.MarketDataService/SubscribeMarketData',
            request_serializer=lambda x: x,
            response_deserializer=lambda x: x,
        )


class MarketDataService_SubscribeMarketDataClient:
    """Client for market data streaming."""
    
    def __init__(self, call):
        self._call = call
    
    def __iter__(self):
        return self
    
    def __next__(self):
        response = self._call.next()
        if response is None:
            raise StopIteration
        return response
    
    def _next(self):
        return self._call.next()
