// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: proto/trading.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MarketDataService_SubscribeMarketData_FullMethodName = "/tradingbot.MarketDataService/SubscribeMarketData"
)

// MarketDataServiceClient is the client API for MarketDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketDataServiceClient interface {
	// Subscribe to market data stream
	SubscribeMarketData(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (MarketDataService_SubscribeMarketDataClient, error)
}

type marketDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketDataServiceClient(cc grpc.ClientConnInterface) MarketDataServiceClient {
	return &marketDataServiceClient{cc}
}

func (c *marketDataServiceClient) SubscribeMarketData(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (MarketDataService_SubscribeMarketDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &MarketDataService_ServiceDesc.Streams[0], MarketDataService_SubscribeMarketData_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &marketDataServiceSubscribeMarketDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MarketDataService_SubscribeMarketDataClient interface {
	Recv() (*MarketData, error)
	grpc.ClientStream
}

type marketDataServiceSubscribeMarketDataClient struct {
	grpc.ClientStream
}

func (x *marketDataServiceSubscribeMarketDataClient) Recv() (*MarketData, error) {
	m := new(MarketData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MarketDataServiceServer is the server API for MarketDataService service.
// All implementations must embed UnimplementedMarketDataServiceServer
// for forward compatibility
type MarketDataServiceServer interface {
	// Subscribe to market data stream
	SubscribeMarketData(*SubscribeRequest, MarketDataService_SubscribeMarketDataServer) error
	mustEmbedUnimplementedMarketDataServiceServer()
}

// UnimplementedMarketDataServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMarketDataServiceServer struct {
}

func (UnimplementedMarketDataServiceServer) SubscribeMarketData(*SubscribeRequest, MarketDataService_SubscribeMarketDataServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeMarketData not implemented")
}
func (UnimplementedMarketDataServiceServer) mustEmbedUnimplementedMarketDataServiceServer() {}

// UnsafeMarketDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketDataServiceServer will
// result in compilation errors.
type UnsafeMarketDataServiceServer interface {
	mustEmbedUnimplementedMarketDataServiceServer()
}

func RegisterMarketDataServiceServer(s grpc.ServiceRegistrar, srv MarketDataServiceServer) {
	s.RegisterService(&MarketDataService_ServiceDesc, srv)
}

func _MarketDataService_SubscribeMarketData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketDataServiceServer).SubscribeMarketData(m, &marketDataServiceSubscribeMarketDataServer{stream})
}

type MarketDataService_SubscribeMarketDataServer interface {
	Send(*MarketData) error
	grpc.ServerStream
}

type marketDataServiceSubscribeMarketDataServer struct {
	grpc.ServerStream
}

func (x *marketDataServiceSubscribeMarketDataServer) Send(m *MarketData) error {
	return x.ServerStream.SendMsg(m)
}

// MarketDataService_ServiceDesc is the grpc.ServiceDesc for MarketDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tradingbot.MarketDataService",
	HandlerType: (*MarketDataServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeMarketData",
			Handler:       _MarketDataService_SubscribeMarketData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/trading.proto",
}

const (
	OrderExecutionService_ExecuteOrder_FullMethodName = "/tradingbot.OrderExecutionService/ExecuteOrder"
	OrderExecutionService_CancelOrder_FullMethodName  = "/tradingbot.OrderExecutionService/CancelOrder"
)

// OrderExecutionServiceClient is the client API for OrderExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderExecutionServiceClient interface {
	// Execute a trading order
	ExecuteOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error)
	// Cancel an order
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error)
}

type orderExecutionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderExecutionServiceClient(cc grpc.ClientConnInterface) OrderExecutionServiceClient {
	return &orderExecutionServiceClient{cc}
}

func (c *orderExecutionServiceClient) ExecuteOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, OrderExecutionService_ExecuteOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderExecutionServiceClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	out := new(CancelOrderResponse)
	err := c.cc.Invoke(ctx, OrderExecutionService_CancelOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderExecutionServiceServer is the server API for OrderExecutionService service.
// All implementations must embed UnimplementedOrderExecutionServiceServer
// for forward compatibility
type OrderExecutionServiceServer interface {
	// Execute a trading order
	ExecuteOrder(context.Context, *OrderRequest) (*OrderResponse, error)
	// Cancel an order
	CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error)
	mustEmbedUnimplementedOrderExecutionServiceServer()
}

// UnimplementedOrderExecutionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOrderExecutionServiceServer struct {
}

func (UnimplementedOrderExecutionServiceServer) ExecuteOrder(context.Context, *OrderRequest) (*OrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteOrder not implemented")
}
func (UnimplementedOrderExecutionServiceServer) CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedOrderExecutionServiceServer) mustEmbedUnimplementedOrderExecutionServiceServer() {}

// UnsafeOrderExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderExecutionServiceServer will
// result in compilation errors.
type UnsafeOrderExecutionServiceServer interface {
	mustEmbedUnimplementedOrderExecutionServiceServer()
}

func RegisterOrderExecutionServiceServer(s grpc.ServiceRegistrar, srv OrderExecutionServiceServer) {
	s.RegisterService(&OrderExecutionService_ServiceDesc, srv)
}

func _OrderExecutionService_ExecuteOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderExecutionServiceServer).ExecuteOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderExecutionService_ExecuteOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderExecutionServiceServer).ExecuteOrder(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderExecutionService_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderExecutionServiceServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderExecutionService_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderExecutionServiceServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderExecutionService_ServiceDesc is the grpc.ServiceDesc for OrderExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tradingbot.OrderExecutionService",
	HandlerType: (*OrderExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteOrder",
			Handler:    _OrderExecutionService_ExecuteOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _OrderExecutionService_CancelOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/trading.proto",
}

const (
	BotStatusService_GetBotStatus_FullMethodName = "/tradingbot.BotStatusService/GetBotStatus"
	BotStatusService_StartBot_FullMethodName     = "/tradingbot.BotStatusService/StartBot"
	BotStatusService_StopBot_FullMethodName      = "/tradingbot.BotStatusService/StopBot"
)

// BotStatusServiceClient is the client API for BotStatusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BotStatusServiceClient interface {
	// Get current bot status
	GetBotStatus(ctx context.Context, in *GetBotStatusRequest, opts ...grpc.CallOption) (*BotStatusResponse, error)
	// Start the bot
	StartBot(ctx context.Context, in *StartBotRequest, opts ...grpc.CallOption) (*StartBotResponse, error)
	// Stop the bot
	StopBot(ctx context.Context, in *StopBotRequest, opts ...grpc.CallOption) (*StopBotResponse, error)
}

type botStatusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBotStatusServiceClient(cc grpc.ClientConnInterface) BotStatusServiceClient {
	return &botStatusServiceClient{cc}
}

func (c *botStatusServiceClient) GetBotStatus(ctx context.Context, in *GetBotStatusRequest, opts ...grpc.CallOption) (*BotStatusResponse, error) {
	out := new(BotStatusResponse)
	err := c.cc.Invoke(ctx, BotStatusService_GetBotStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botStatusServiceClient) StartBot(ctx context.Context, in *StartBotRequest, opts ...grpc.CallOption) (*StartBotResponse, error) {
	out := new(StartBotResponse)
	err := c.cc.Invoke(ctx, BotStatusService_StartBot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botStatusServiceClient) StopBot(ctx context.Context, in *StopBotRequest, opts ...grpc.CallOption) (*StopBotResponse, error) {
	out := new(StopBotResponse)
	err := c.cc.Invoke(ctx, BotStatusService_StopBot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BotStatusServiceServer is the server API for BotStatusService service.
// All implementations must embed UnimplementedBotStatusServiceServer
// for forward compatibility
type BotStatusServiceServer interface {
	// Get current bot status
	GetBotStatus(context.Context, *GetBotStatusRequest) (*BotStatusResponse, error)
	// Start the bot
	StartBot(context.Context, *StartBotRequest) (*StartBotResponse, error)
	// Stop the bot
	StopBot(context.Context, *StopBotRequest) (*StopBotResponse, error)
	mustEmbedUnimplementedBotStatusServiceServer()
}

// UnimplementedBotStatusServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBotStatusServiceServer struct {
}

func (UnimplementedBotStatusServiceServer) GetBotStatus(context.Context, *GetBotStatusRequest) (*BotStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBotStatus not implemented")
}
func (UnimplementedBotStatusServiceServer) StartBot(context.Context, *StartBotRequest) (*StartBotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartBot not implemented")
}
func (UnimplementedBotStatusServiceServer) StopBot(context.Context, *StopBotRequest) (*StopBotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopBot not implemented")
}
func (UnimplementedBotStatusServiceServer) mustEmbedUnimplementedBotStatusServiceServer() {}

// UnsafeBotStatusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BotStatusServiceServer will
// result in compilation errors.
type UnsafeBotStatusServiceServer interface {
	mustEmbedUnimplementedBotStatusServiceServer()
}

func RegisterBotStatusServiceServer(s grpc.ServiceRegistrar, srv BotStatusServiceServer) {
	s.RegisterService(&BotStatusService_ServiceDesc, srv)
}

func _BotStatusService_GetBotStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBotStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotStatusServiceServer).GetBotStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotStatusService_GetBotStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotStatusServiceServer).GetBotStatus(ctx, req.(*GetBotStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotStatusService_StartBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotStatusServiceServer).StartBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotStatusService_StartBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotStatusServiceServer).StartBot(ctx, req.(*StartBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotStatusService_StopBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotStatusServiceServer).StopBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotStatusService_StopBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotStatusServiceServer).StopBot(ctx, req.(*StopBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BotStatusService_ServiceDesc is the grpc.ServiceDesc for BotStatusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BotStatusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tradingbot.BotStatusService",
	HandlerType: (*BotStatusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBotStatus",
			Handler:    _BotStatusService_GetBotStatus_Handler,
		},
		{
			MethodName: "StartBot",
			Handler:    _BotStatusService_StartBot_Handler,
		},
		{
			MethodName: "StopBot",
			Handler:    _BotStatusService_StopBot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/trading.proto",
}

const (
	DexService_GetQuote_FullMethodName     = "/tradingbot.DexService/GetQuote"
	DexService_Swap_FullMethodName         = "/tradingbot.DexService/Swap"
	DexService_GetTokenInfo_FullMethodName = "/tradingbot.DexService/GetTokenInfo"
	DexService_GetBalance_FullMethodName   = "/tradingbot.DexService/GetBalance"
)

// DexServiceClient is the client API for DexService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DexServiceClient interface {
	GetQuote(ctx context.Context, in *GetQuoteRequest, opts ...grpc.CallOption) (*QuoteResponse, error)
	Swap(ctx context.Context, in *SwapRequest, opts ...grpc.CallOption) (*SwapTxResponse, error)
	GetTokenInfo(ctx context.Context, in *TokenInfoRequest, opts ...grpc.CallOption) (*TokenInfoResponse, error)
	GetBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
}

type dexServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDexServiceClient(cc grpc.ClientConnInterface) DexServiceClient {
	return &dexServiceClient{cc}
}

func (c *dexServiceClient) GetQuote(ctx context.Context, in *GetQuoteRequest, opts ...grpc.CallOption) (*QuoteResponse, error) {
	out := new(QuoteResponse)
	err := c.cc.Invoke(ctx, DexService_GetQuote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexServiceClient) Swap(ctx context.Context, in *SwapRequest, opts ...grpc.CallOption) (*SwapTxResponse, error) {
	out := new(SwapTxResponse)
	err := c.cc.Invoke(ctx, DexService_Swap_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexServiceClient) GetTokenInfo(ctx context.Context, in *TokenInfoRequest, opts ...grpc.CallOption) (*TokenInfoResponse, error) {
	out := new(TokenInfoResponse)
	err := c.cc.Invoke(ctx, DexService_GetTokenInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexServiceClient) GetBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, DexService_GetBalance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DexServiceServer is the server API for DexService service.
// All implementations must embed UnimplementedDexServiceServer
// for forward compatibility
type DexServiceServer interface {
	GetQuote(context.Context, *GetQuoteRequest) (*QuoteResponse, error)
	Swap(context.Context, *SwapRequest) (*SwapTxResponse, error)
	GetTokenInfo(context.Context, *TokenInfoRequest) (*TokenInfoResponse, error)
	GetBalance(context.Context, *BalanceRequest) (*BalanceResponse, error)
	mustEmbedUnimplementedDexServiceServer()
}

// UnimplementedDexServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDexServiceServer struct {
}

func (UnimplementedDexServiceServer) GetQuote(context.Context, *GetQuoteRequest) (*QuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuote not implemented")
}
func (UnimplementedDexServiceServer) Swap(context.Context, *SwapRequest) (*SwapTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Swap not implemented")
}
func (UnimplementedDexServiceServer) GetTokenInfo(context.Context, *TokenInfoRequest) (*TokenInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTokenInfo not implemented")
}
func (UnimplementedDexServiceServer) GetBalance(context.Context, *BalanceRequest) (*BalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedDexServiceServer) mustEmbedUnimplementedDexServiceServer() {}

// UnsafeDexServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DexServiceServer will
// result in compilation errors.
type UnsafeDexServiceServer interface {
	mustEmbedUnimplementedDexServiceServer()
}

func RegisterDexServiceServer(s grpc.ServiceRegistrar, srv DexServiceServer) {
	s.RegisterService(&DexService_ServiceDesc, srv)
}

func _DexService_GetQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServiceServer).GetQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DexService_GetQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServiceServer).GetQuote(ctx, req.(*GetQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DexService_Swap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServiceServer).Swap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DexService_Swap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServiceServer).Swap(ctx, req.(*SwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DexService_GetTokenInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServiceServer).GetTokenInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DexService_GetTokenInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServiceServer).GetTokenInfo(ctx, req.(*TokenInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DexService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DexService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServiceServer).GetBalance(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DexService_ServiceDesc is the grpc.ServiceDesc for DexService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DexService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tradingbot.DexService",
	HandlerType: (*DexServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetQuote",
			Handler:    _DexService_GetQuote_Handler,
		},
		{
			MethodName: "Swap",
			Handler:    _DexService_Swap_Handler,
		},
		{
			MethodName: "GetTokenInfo",
			Handler:    _DexService_GetTokenInfo_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _DexService_GetBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/trading.proto",
}
